name: Contrast AI SmartFix
true:
  pull_request:
    types:
    - closed
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch: null
permissions:
  contents: write
  pull-requests: write
jobs:
  generate_fixes:
    name: Generate Fixes
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Contrast AI SmartFix - Generate Fixes Action
      uses: Contrast-Security-OSS/contrast-ai-smartfix-action@v1
      with:
        contrast_host: ${{ vars.CONTRAST_HOST }}
        contrast_org_id: ${{ vars.CONTRAST_ORG_ID }}
        contrast_app_id: ${{ vars.CONTRAST_APP_ID }}
        contrast_authorization_key: ${{ secrets.CONTRAST_AUTHORIZATION_KEY }}
        contrast_api_key: ${{ secrets.CONTRAST_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        base_branch: ${{ github.event.repository.default_branch }}
        build_command: cd services/frontgateservice && ./mvnw clean test -B
        max_open_prs: 2
        use_contrast_llm: true
  handle_pr_merge:
    name: Handle PR Merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref,
      'smartfix/remediation-')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Notify Contrast on PR Merge
      uses: Contrast-Security-OSS/contrast-ai-smartfix-action@fix/separate-label-addition
      with:
        run_task: merge
        github_token: ${{ secrets.GITHUB_TOKEN }}
        contrast_host: ${{ vars.CONTRAST_HOST }}
        contrast_org_id: ${{ vars.CONTRAST_ORG_ID }}
        contrast_app_id: ${{ vars.CONTRAST_APP_ID }}
        contrast_authorization_key: ${{ secrets.CONTRAST_AUTHORIZATION_KEY }}
        contrast_api_key: ${{ secrets.CONTRAST_API_KEY }}
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
  handle_pr_closed:
    name: Handle PR Close
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false && contains(github.event.pull_request.head.ref,
      'smartfix/remediation-')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Notify Contrast on PR Closed
      uses: Contrast-Security-OSS/contrast-ai-smartfix-action@fix/separate-label-addition
      with:
        run_task: closed
        github_token: ${{ secrets.GITHUB_TOKEN }}
        contrast_host: ${{ vars.CONTRAST_HOST }}
        contrast_org_id: ${{ vars.CONTRAST_ORG_ID }}
        contrast_app_id: ${{ vars.CONTRAST_APP_ID }}
        contrast_authorization_key: ${{ secrets.CONTRAST_AUTHORIZATION_KEY }}
        contrast_api_key: ${{ secrets.CONTRAST_API_KEY }}
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
